"""add content engine domain models

Revision ID: 26462e3ed1cc
Revises: 4e6e6302b51b
Create Date: 2026-07-03 21:23:32.997162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26462e3ed1cc'
down_revision: Union[str, Sequence[str], None] = '4e6e6302b51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solutions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_solutions_slug')
    )
    op.create_index('ix_solutions_is_builtin', 'solutions', ['is_builtin'], unique=False)
    op.create_index('ix_solutions_name', 'solutions', ['name'], unique=False)
    op.create_table('editable_component_definitions',
    sa.Column('solution_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('kind', sa.Enum('SINGLETON', 'COLLECTION', name='editablecomponentkind'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('editor_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'key', name='uq_editable_component_definitions_site_id_key')
    )
    op.create_index(op.f('ix_editable_component_definitions_display_order'), 'editable_component_definitions', ['display_order'], unique=False)
    op.create_index(op.f('ix_editable_component_definitions_key'), 'editable_component_definitions', ['key'], unique=False)
    op.create_index(op.f('ix_editable_component_definitions_kind'), 'editable_component_definitions', ['kind'], unique=False)
    op.create_index(op.f('ix_editable_component_definitions_site_id'), 'editable_component_definitions', ['site_id'], unique=False)
    op.create_index('ix_editable_component_definitions_site_id_display_order', 'editable_component_definitions', ['site_id', 'display_order'], unique=False)
    op.create_index('ix_editable_component_definitions_site_id_kind', 'editable_component_definitions', ['site_id', 'kind'], unique=False)
    op.create_index(op.f('ix_editable_component_definitions_solution_id'), 'editable_component_definitions', ['solution_id'], unique=False)
    op.create_table('content_entries',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['editable_component_definitions.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'slug', name='uq_content_entries_site_id_slug')
    )
    op.create_index(op.f('ix_content_entries_definition_id'), 'content_entries', ['definition_id'], unique=False)
    op.create_index('ix_content_entries_definition_id_sort_order', 'content_entries', ['definition_id', 'sort_order'], unique=False)
    op.create_index('ix_content_entries_definition_id_status', 'content_entries', ['definition_id', 'status'], unique=False)
    op.create_index(op.f('ix_content_entries_site_id'), 'content_entries', ['site_id'], unique=False)
    op.create_index('ix_content_entries_site_id_status', 'content_entries', ['site_id', 'status'], unique=False)
    op.create_index(op.f('ix_content_entries_sort_order'), 'content_entries', ['sort_order'], unique=False)
    op.create_index(op.f('ix_content_entries_status'), 'content_entries', ['status'], unique=False)
    op.create_index('ix_content_entries_title', 'content_entries', ['title'], unique=False)
    op.create_index(op.f('ix_sites_owner_id'), 'sites', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_owner_id'), table_name='sites')
    op.drop_index('ix_content_entries_title', table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_status'), table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_sort_order'), table_name='content_entries')
    op.drop_index('ix_content_entries_site_id_status', table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_site_id'), table_name='content_entries')
    op.drop_index('ix_content_entries_definition_id_status', table_name='content_entries')
    op.drop_index('ix_content_entries_definition_id_sort_order', table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_definition_id'), table_name='content_entries')
    op.drop_table('content_entries')
    op.drop_index(op.f('ix_editable_component_definitions_solution_id'), table_name='editable_component_definitions')
    op.drop_index('ix_editable_component_definitions_site_id_kind', table_name='editable_component_definitions')
    op.drop_index('ix_editable_component_definitions_site_id_display_order', table_name='editable_component_definitions')
    op.drop_index(op.f('ix_editable_component_definitions_site_id'), table_name='editable_component_definitions')
    op.drop_index(op.f('ix_editable_component_definitions_kind'), table_name='editable_component_definitions')
    op.drop_index(op.f('ix_editable_component_definitions_key'), table_name='editable_component_definitions')
    op.drop_index(op.f('ix_editable_component_definitions_display_order'), table_name='editable_component_definitions')
    op.drop_table('editable_component_definitions')
    op.drop_index('ix_solutions_name', table_name='solutions')
    op.drop_index('ix_solutions_is_builtin', table_name='solutions')
    op.drop_table('solutions')
    # ### end Alembic commands ###
