"""fixing timezone issue

Revision ID: 467df3a539ab
Revises: 30de3a6f0271
Create Date: 2026-07-06 22:28:05.660834

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "467df3a539ab"
down_revision: str | Sequence[str] | None = "30de3a6f0271"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
