"""add verification_codes table for development users only

Revision ID: 56afa3e28f95
Revises: 5bb95eff3e9d
Create Date: 2026-07-12 12:20:20.510887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56afa3e28f95'
down_revision: Union[str, Sequence[str], None] = '5bb95eff3e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
