"""add Form, FormSubmission, MediaAsset and AccessToken models.

Revision ID: 594f982e6f5d
Revises: 26462e3ed1cc
Create Date: 2026-07-05 20:00:38.931674

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "594f982e6f5d"
down_revision: Union[str, Sequence[str], None] = "26462e3ed1cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_tokens",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_access_tokens_token_hash"),
    )
    op.create_index(
        op.f("ix_access_tokens_site_id"), "access_tokens", ["site_id"], unique=False
    )
    op.create_index(
        op.f("ix_access_tokens_token_hash"),
        "access_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "forms",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "slug", name="uq_forms_site_id_slug"),
    )
    op.create_index("ix_forms_site_id", "forms", ["site_id"], unique=False)
    op.create_index(op.f("ix_forms_slug"), "forms", ["slug"], unique=False)
    op.create_table(
        "media_assets",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=True),
        sa.Column("extension", sa.String(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("alt_text", sa.String(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key", name="uq_media_assets_storage_key"),
    )
    op.create_index(
        op.f("ix_media_assets_site_id"), "media_assets", ["site_id"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_storage_key"),
        "media_assets",
        ["storage_key"],
        unique=True,
    )
    op.create_table(
        "form_submissions",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSED", "SPAM", name="formsubmissionstatus"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["forms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_form_submissions_form_id"),
        "form_submissions",
        ["form_id"],
        unique=False,
    )
    op.create_index(
        "ix_form_submissions_status", "form_submissions", ["status"], unique=False
    )
    op.create_index(
        "ix_form_submissions_submitted_at",
        "form_submissions",
        ["submitted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_form_submissions_submitted_at", table_name="form_submissions")
    op.drop_index("ix_form_submissions_status", table_name="form_submissions")
    op.drop_index(op.f("ix_form_submissions_form_id"), table_name="form_submissions")
    op.drop_table("form_submissions")
    op.drop_index(op.f("ix_media_assets_storage_key"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_site_id"), table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index(op.f("ix_forms_slug"), table_name="forms")
    op.drop_index("ix_forms_site_id", table_name="forms")
    op.drop_table("forms")
    op.drop_index(op.f("ix_access_tokens_token_hash"), table_name="access_tokens")
    op.drop_index(op.f("ix_access_tokens_site_id"), table_name="access_tokens")
    op.drop_table("access_tokens")
    # ### end Alembic commands ###
